"""
state.py — Shared state for the multi-agent pipeline.
All agents read/write to this central state object.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class TopicConfig:
    """Generated by Agent 1 (Query Architect) — consumed by all other agents."""
    topic: str = ""
    sub_topics: list[str] = field(default_factory=list)
    search_queries: list[str] = field(default_factory=list)
    content_keywords: list[str] = field(default_factory=list)
    domain_config: dict = field(default_factory=dict)
    field_definitions: dict[str, str] = field(default_factory=dict)
    field_examples: dict[str, str] = field(default_factory=dict)
    merge_config: dict = field(default_factory=dict)   # {"identity": [...], "content": [...]}
    section_headers: list[str] = field(default_factory=list)
    url_patterns: dict[str, str] = field(default_factory=dict)
    paywall_domains: list[str] = field(default_factory=list)
    paywall_signals: list[str] = field(default_factory=list)
    # Per-domain custom headers (domain_substring → {header: value})
    custom_headers: dict[str, dict[str, str]] = field(default_factory=dict)


@dataclass
class BlockedSource:
    """Tracks a source that was blocked/inaccessible."""
    url: str = ""
    reason: str = ""          # paywall | cloudflare | captcha | 403 | 429_exhausted | timeout | bot_detect
    status_code: int = 0
    timestamp: float = field(default_factory=time.time)
    details: str = ""         # extra context (e.g. "Cloudflare challenge page detected")


@dataclass
class DocumentObject:
    """Unified document model produced by Agent 3 (Ingestion)."""
    source: str = ""                               # URL or file path
    text_blocks: list[str] = field(default_factory=list)  # cleaned text chunks
    full_text: str = ""                            # complete extracted text
    tables: list[dict] = field(default_factory=list)      # [{csv: str, page: int, caption: str}]
    figures: list[dict] = field(default_factory=list)      # [{caption: str, page: int, image_path: str}]
    method: str = "unknown"                        # pdf | html | local_pdf | ocr
    metadata: dict = field(default_factory=dict)   # DOI, title, etc from meta tags
    pdf_path: str | None = None
    html: str = ""
    dataset_links: list[dict] = field(default_factory=list)
    supplement_links: list[dict] = field(default_factory=list)


@dataclass
class ExtractedRow:
    """A single extracted row with confidence metadata."""
    data: dict[str, str] = field(default_factory=dict)          # column → value
    confidence: dict[str, str] = field(default_factory=dict)    # column → "high"/"low"/"missing"
    source_url: str = ""
    row_confidence: float = 1.0
    issues: list[str] = field(default_factory=list)


@dataclass 
class GapEntry:
    """Tracks a missing value that needs filling."""
    column: str = ""
    source_url: str = ""
    row_index: int = 0
    attempts: int = 0
    resolved: bool = False


@dataclass
class SharedState:
    """Central state shared across all agents during a pipeline run."""
    
    # ── User input ────────────────────────────────────────────────────────
    dataset_name: str = ""
    description: str = ""
    columns: list[str] = field(default_factory=list)
    min_rows: int = 50
    max_sources: int = 15
    quality_threshold: str = "high"
    
    # ── Topic config (Agent 1 output) ─────────────────────────────────────
    topic_config: TopicConfig = field(default_factory=TopicConfig)
    
    # ── Source tracking (Agent 2) ─────────────────────────────────────────
    candidate_urls: list[str] = field(default_factory=list)
    triage_passed: list[str] = field(default_factory=list)
    triage_failed: list[str] = field(default_factory=list)
    seen_url_hashes: set[str] = field(default_factory=set)
    seen_pdf_hashes: set[str] = field(default_factory=set)
    
    # ── Blocked sources ───────────────────────────────────────────────────
    blocked_sources: list[BlockedSource] = field(default_factory=list)
    
    # ── Documents (Agent 3 output) ────────────────────────────────────────
    documents: list[DocumentObject] = field(default_factory=list)
    
    # ── Extracted data (Agent 4/5 output) ─────────────────────────────────
    extracted_rows: list[ExtractedRow] = field(default_factory=list)
    
    # ── Gap registry (Agent 5) ────────────────────────────────────────────
    gap_registry: list[GapEntry] = field(default_factory=list)
    
    # ── Validation results (Agent 6 output) ───────────────────────────────
    accepted_rows: list[dict] = field(default_factory=list)
    rejected_rows: list[dict] = field(default_factory=list)
    null_rate: float = 1.0
    needs_more_sources: bool = False
    
    # ── Pipeline control ──────────────────────────────────────────────────
    current_iteration: int = 0
    max_iterations: int = 3
    output_path: str = "data/outputs/output.csv"
    start_time: float = field(default_factory=time.time)
    
    # ── Conversation memory (chatbot) ─────────────────────────────────────
    conversation_memory: list[dict] = field(default_factory=list)
    
    # ── Incremental growth tracking ────────────────────────────────────────
    _existing_sigs: set[str] = field(default_factory=set)
    _existing_row_count: int = 0
    
    # ── Event log ─────────────────────────────────────────────────────────
    event_log: list[dict] = field(default_factory=list)
    
    def load_existing_rows(self, csv_path: str) -> int:
        """
        Load rows from an existing output CSV into the state so the pipeline
        can append rather than overwrite.

        Returns the number of rows loaded.
        """
        import csv as csv_mod
        from pathlib import Path as P

        path = P(csv_path)
        if not path.exists() or path.stat().st_size == 0:
            return 0

        try:
            with open(path, newline="", encoding="utf-8-sig") as fh:
                reader = csv_mod.DictReader(fh)
                loaded = 0
                data_cols = [c for c in self.columns if c not in ("Source_URL", "row_confidence")]
                for record in reader:
                    self.accepted_rows.append(dict(record))
                    # Build dedup signature
                    sig = "|".join(
                        str(record.get(c, "")).strip().lower() for c in data_cols
                    )
                    self._existing_sigs.add(sig)
                    # Track seen URLs
                    url = record.get("Source_URL", "")
                    if url:
                        self.seen_url_hashes.add(url)
                    loaded += 1
                self._existing_row_count = loaded
                return loaded
        except Exception:
            return 0

    def is_duplicate_row(self, row_data: dict) -> bool:
        """Check if a row already exists in the previously loaded data."""
        data_cols = [c for c in self.columns if c not in ("Source_URL", "row_confidence")]
        sig = "|".join(
            str(row_data.get(c, "")).strip().lower() for c in data_cols
        )
        return sig in self._existing_sigs

    def log_event(self, agent: str, event: str, details: str = ""):
        """Log a pipeline event for debugging and user visibility."""
        self.event_log.append({
            "time": time.time() - self.start_time,
            "agent": agent,
            "event": event,
            "details": details,
        })
    
    def add_blocked(self, url: str, reason: str, status_code: int = 0, details: str = ""):
        """Record a blocked/inaccessible source."""
        self.blocked_sources.append(BlockedSource(
            url=url, reason=reason, status_code=status_code, details=details,
        ))
        self.log_event("ingestion", "blocked", f"{reason}: {url[:60]}")
    
    def get_flat_rows(self) -> list[dict]:
        """Convert ExtractedRows to flat dicts for DataFrame/CSV."""
        rows = []
        for er in self.extracted_rows:
            row = dict(er.data)
            row["Source_URL"] = er.source_url
            row["row_confidence"] = er.row_confidence
            rows.append(row)
        return rows
    
    def summary(self) -> str:
        """One-liner status for console output."""
        elapsed = time.time() - self.start_time
        return (
            f"Rows: {len(self.extracted_rows)} | "
            f"Sources: {len(self.documents)} | "
            f"Blocked: {len(self.blocked_sources)} | "
            f"Null rate: {self.null_rate:.0%} | "
            f"Iteration: {self.current_iteration}/{self.max_iterations} | "
            f"Time: {elapsed:.0f}s"
        )
    
    def save_checkpoint(self, path: str | None = None):
        """Save state to JSON for crash recovery.
        
        When *path* is ``None`` the checkpoint is written next to the
        current ``output_path`` inside the topic workspace.
        """
        if path is None:
            import os
            path = os.path.join(
                os.path.dirname(self.output_path) or "data/outputs",
                "checkpoint.json",
            )
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        data = {
            "dataset_name": self.dataset_name,
            "columns": self.columns,
            "rows": self.get_flat_rows(),
            "iteration": self.current_iteration,
            "null_rate": self.null_rate,
            "sources_processed": len(self.documents),
            "blocked_sources": [
                {"url": b.url, "reason": b.reason, "status_code": b.status_code, "details": b.details}
                for b in self.blocked_sources
            ],
            "event_log": self.event_log[-50:],  # last 50 events
        }
        Path(path).write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
